"""
Hook fire simulator tests.

Each test sends a mock payload via stdin to the journal.py hook command and
verifies that the expected JSONL record is written to local_log_dir.  Tests
can be run on any platform (mac/windows) over SSH without installing Codex or
Cursor — that is the whole point.

Run:
    python3 skills/ai-worklog/scripts/test_hook_fire.py
    python -m pytest skills/ai-worklog/scripts/test_hook_fire.py -v
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import unittest
from datetime import date
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPTS_DIR.parent  # skills/ai-worklog/
JOURNAL_PY = SCRIPTS_DIR / "journal.py"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))


def load_script(name: str):
    path = SCRIPTS_DIR / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


install = load_script("install")

MOCK_PAYLOADS: dict[str, dict] = {
    "codex/SessionStart": {
        "hook_event_name": "SessionStart",
        "session_id": "test-session-001",
        "model": "o3",
        "cwd": "/tmp/test-project",
    },
    "codex/UserPromptSubmit": {
        "hook_event_name": "UserPromptSubmit",
        "session_id": "test-session-001",
        "turn_id": "turn-1",
        "prompt": "test prompt from hook fire simulator",
        "cwd": "/tmp/test-project",
    },
    "codex/PostToolUse/exec": {
        "hook_event_name": "PostToolUse",
        "session_id": "test-session-001",
        "turn_id": "turn-1",
        "tool_name": "exec",
        "tool_input": {"cmd": "echo hello", "workdir": "/tmp/test-project"},
        "tool_response": "hello",
        "exit_code": 0,
    },
    "codex/PostToolUse/apply_patch": {
        "hook_event_name": "PostToolUse",
        "session_id": "test-session-001",
        "turn_id": "turn-1",
        "tool_name": "apply_patch",
        "tool_input": "*** Begin Patch\n*** Add File: test_output.py\n+# generated\n+x = 1\n*** End Patch",
        "tool_response": "OK",
        "exit_code": 0,
    },
    "codex/Stop": {
        "hook_event_name": "Stop",
        "session_id": "test-session-001",
        "cwd": "/tmp/test-project",
        "last_assistant_message": "Done.",
    },
    "cursor/sessionStart": {
        "hook_event_name": "sessionStart",
        "session_id": "cursor-test-001",
        "workspacePath": "/tmp/test-project",
    },
    "cursor/beforeSubmitPrompt": {
        "hook_event_name": "beforeSubmitPrompt",
        "session_id": "cursor-test-001",
        "prompt": "test prompt from hook fire simulator",
    },
    "cursor/postToolUse": {
        "hook_event_name": "postToolUse",
        "session_id": "cursor-test-001",
        "tool_name": "run_terminal_cmd",
        "tool_input": {"command": "echo hello"},
        "tool_response": "hello",
        "exit_code": 0,
    },
    "cursor/postToolUseFailure": {
        "hook_event_name": "postToolUseFailure",
        "session_id": "cursor-test-001",
        "tool_name": "run_terminal_cmd",
        "tool_input": {"command": "exit 1"},
        "error": "Process exited with code 1",
        "exit_code": 1,
    },
    "cursor/afterFileEdit": {
        "hook_event_name": "afterFileEdit",
        "session_id": "cursor-test-001",
        "path": "test_output.py",
        "content": "# generated by hook fire simulator\nx = 1\n",
    },
    "cursor/afterAgentResponse": {
        "hook_event_name": "afterAgentResponse",
        "session_id": "cursor-test-001",
        "response": "hook fire simulator agent response",
    },
    "cursor/stop": {
        "hook_event_name": "stop",
        "session_id": "cursor-test-001",
        "workspacePath": "/tmp/test-project",
    },
}


def fire_hook(payload: dict, surface: str, config_path: Path) -> subprocess.CompletedProcess:
    command = install.python_command(SKILL_DIR, surface, config_path)
    env = {**os.environ, "AI_WORKLOG_DISABLE_BACKGROUND": "1"}
    return subprocess.run(
        command,
        shell=True,
        input=json.dumps(payload).encode(),
        capture_output=True,
        env=env,
        timeout=15,
    )


def read_today_events(local_log_dir: Path) -> list[dict]:
    today = date.today().isoformat()
    jsonl = local_log_dir / f"{today}.jsonl"
    if not jsonl.exists():
        return []
    records = []
    for line in jsonl.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


def first_event(records: list[dict]) -> dict | None:
    for r in records:
        if r.get("record_type") == "event":
            return r
    return None


class HookFireTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        root = Path(self._tmp.name)
        self.local_log_dir = root / "events"
        self.local_log_dir.mkdir()
        self.config_path = root / "config.json"
        self.config_path.write_text(
            json.dumps(
                {
                    "enabled": True,
                    "collection_level": "full",
                    "local_log_dir": str(self.local_log_dir),
                    "snapshot_log_dir": str(root / "snapshots"),
                    "state_path": str(root / "state.json"),
                    "server_url": None,
                }
            )
            + "\n",
            encoding="utf-8",
        )

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def assertHookSucceeds(self, payload: dict, surface: str) -> list[dict]:
        result = fire_hook(payload, surface, self.config_path)
        self.assertEqual(
            result.returncode,
            0,
            msg=f"hook exited {result.returncode}; stderr={result.stderr.decode(errors='replace')[:500]}",
        )
        return read_today_events(self.local_log_dir)

    # --- Codex ---

    def test_codex_session_start(self) -> None:
        payload = MOCK_PAYLOADS["codex/SessionStart"]
        records = self.assertHookSucceeds(payload, "codex")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "session")
        self.assertEqual(event["session_id"], "test-session-001")
        self.assertEqual(event["surface"], "codex")

    def test_codex_user_prompt_submit(self) -> None:
        payload = MOCK_PAYLOADS["codex/UserPromptSubmit"]
        records = self.assertHookSucceeds(payload, "codex")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "prompt")
        self.assertIn("prompt", str(event.get("content", {}).get("prompt", "")))

    def test_codex_post_tool_use_exec(self) -> None:
        payload = MOCK_PAYLOADS["codex/PostToolUse/exec"]
        records = self.assertHookSucceeds(payload, "codex")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "tool")
        self.assertEqual(event["tool"]["name"], "exec")
        self.assertEqual(event["tool"]["exit_code"], 0)
        self.assertTrue(event["operation"]["success"])

    def test_codex_post_tool_use_apply_patch(self) -> None:
        payload = MOCK_PAYLOADS["codex/PostToolUse/apply_patch"]
        records = self.assertHookSucceeds(payload, "codex")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["tool"]["name"], "apply_patch")
        self.assertTrue(event["operation"]["success"])
        # patch text as string is stored in raw_hook_input; file extraction
        # happens at analysis time via parse_patch_text(), not in the record
        self.assertIn("Begin Patch", str(event.get("raw_hook_input", "")))

    def test_codex_stop(self) -> None:
        payload = MOCK_PAYLOADS["codex/Stop"]
        records = self.assertHookSucceeds(payload, "codex")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["phase"], "stop")

    # --- Cursor ---

    def test_cursor_session_start(self) -> None:
        payload = MOCK_PAYLOADS["cursor/sessionStart"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["surface"], "cursor")
        self.assertEqual(event["session_id"], "cursor-test-001")
        self.assertEqual(event["operation"]["category"], "session")

    def test_cursor_before_submit_prompt(self) -> None:
        payload = MOCK_PAYLOADS["cursor/beforeSubmitPrompt"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "prompt")
        self.assertIn("test prompt", str(event.get("content", {}).get("prompt", "")))

    def test_cursor_post_tool_use(self) -> None:
        payload = MOCK_PAYLOADS["cursor/postToolUse"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "tool")
        self.assertEqual(event["tool"]["name"], "run_terminal_cmd")
        self.assertEqual(event["tool"]["exit_code"], 0)
        self.assertTrue(event["operation"]["success"])

    def test_cursor_post_tool_use_failure(self) -> None:
        payload = MOCK_PAYLOADS["cursor/postToolUseFailure"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["phase"], "failure")
        self.assertFalse(event["operation"]["success"])

    def test_cursor_after_file_edit(self) -> None:
        payload = MOCK_PAYLOADS["cursor/afterFileEdit"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["category"], "file_edit")
        self.assertIn("test_output.py", event["tool"]["files_written"])

    def test_cursor_after_agent_response(self) -> None:
        payload = MOCK_PAYLOADS["cursor/afterAgentResponse"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertIn("agent response", str(event.get("content", {}).get("response", "")))

    def test_cursor_stop(self) -> None:
        payload = MOCK_PAYLOADS["cursor/stop"]
        records = self.assertHookSucceeds(payload, "cursor")
        event = first_event(records)
        self.assertIsNotNone(event)
        self.assertEqual(event["operation"]["phase"], "stop")


if __name__ == "__main__":
    unittest.main()
